name: 自动同步备份（修复令牌错误）
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

# 公共仓库需要添加此权限配置
permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: 检查当前备份仓库
        uses: actions/checkout@v4
        with:
          # 使用默认令牌（适用于公共仓库）
          persist-credentials: true
          # 如果使用自定义令牌，请确保密钥存在
          # token: ${{ secrets.MY_GITHUB_TOKEN }}

      # 其余步骤保持不变...
      - name: 配置Git
        run: |
          git config --global user.name "QuarterOptic"
          git config --global user.email "sztao2000@icloud.com"

      # 同步备份步骤...
      - name: 同步目标仓库并强制生成备份
        run: |
          # 你的同步逻辑...

      - name: 提交备份
        run: |
          git add backups/
          git commit --allow-empty -m "自动备份: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
    
